FROM base/archlinux

RUN pacman -Sy --noconfirm archlinux-keyring
RUN pacman -Syu --noconfirm && pacman-db-upgrade
RUN pacman -Sy && pacman -S --noconfirm ca-certificates-mozilla && pacman -S llvm clang make linux-headers

RUN mkdir -p /src

WORKDIR /src
