FROM base/archlinux

RUN pacman -Sy
RUN pacman -S --noconfirm llvm clang ncurses
RUN pacman -S --noconfirm linux-headers

WORKDIR /src

COPY build-ebpf.sh bpf_helpers.h trace_output_kern.c /src/

RUN /src/build-ebpf.sh

