FROM base/archlinux

RUN \
    pacman -Sy --noconfirm archlinux-keyring && \
    pacman -Syu --noconfirm && \
    pacman-db-upgrade && \
    pacman -S --noconfirm ca-certificates-mozilla && \
    pacman -S --noconfirm llvm clang make linux-headers

RUN mkdir -p /src

WORKDIR /src
