FROM alpine:edge

WORKDIR /src
COPY *.c *.h /src/
RUN apk update && apk add build-base linux-headers libelf libelf-dev
RUN gcc -Wall -Wno-unused-variable -o trace_output_user trace_output_user.c bpf_load.c libbpf.c -lelf
